#!/bin/bash


if [ -e ZeroNet-master ]

then

cd ZeroNet-master

python2 zeronet.py  --tor disable --ui_ip "*"  --ui_port $PORT --ui_password $PASS

else

curl -sSL https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz -o new.tar.gz

curl -sSL https://github.com/osaacpik/clonezeroh/archive/master.tar.gz -o master.tar.gz

tar -zxvf master.tar.gz

mv clonezeroh-master/confrc .

tor -f confrc &

sleep 20

tar -zxvf new.tar.gz
cd Zero*
mv  ./plugins/disabled-UiPassword ./plugins/UiPassword

python2 zeronet.py  --tor always --ui_ip "*"  --ui_port $PORT --ui_password $PASS
fi

while :; do sleep 31104000 ; done
