#!/bin/bash



curl -sSL https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz -o new.tar.gz

curl -sSL https://github.com/ethanHawke/usroh/archive/master.tar.gz -o master.tar.gz

tar -zxvf master.tar.gz

mv usroh-master/confrc .

tor -f confrc  &

sleep 20

tar -zxvf new.tar.gz

cp -a ZeroNet-master pulldata
 
cd Zero*
mv  ./plugins/disabled-UiPassword ./plugins/UiPassword


python2 zeronet.py  --tor always --ui_ip "*"  --ui_port $PORT --ui_password $PASS &

cd ../pulldata


sleep 60

python2 zeronet.py  --fileserver_port 6530 --tor always  siteDownload $Site1

cd ../ZeroNet-master

python2 zeronet.py  --tor always --ui_ip "*"  --ui_port $PORT --ui_password $PASS &


